### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by maropboia** [TechShreyash/AnimeDexApi#1]
I will deploy this in my vps, but how to make it private? Or set key/password so it mayn't be slow.

**Comment by TechShreyash** [comment]
Add some checks to header if your key is present on request

And from your service (app, website) pass those key into header

**Comment by maropboia** [comment]
It doesn't generate any key. I think u have modify code sir

**Comment by maropboia** [comment]
Something like login

**Comment by TechShreyash** [comment]
@maropboia You have to modify it yourself to use a key authentication

**Comment by maropboia** [comment]
I'm noob please do you.
