### ISSUE TITLE
use multiple baseurl in index js

### ISSUE THREAD

**Issue by NEWBIENOOB-0** [TechShreyash/AnimeDexApi#2]
var BaseURL = "https://gogoanime3.co";
var BaseURL1 = "https://gogoanime3.co";
var BaseURL2 = "https://gogoanime3.co";

use multiple baseurl in index js

**Comment by TechShreyash** [comment]
> var BaseURL = "https://gogoanime3.co"; var BaseURL1 = "https://gogoanime3.co"; var BaseURL2 = "https://gogoanime3.co";

They are same

**Comment by NEWBIENOOB-0** [comment]
> > var BaseURL = "https://gogoanime3.co"; var BaseURL1 = "https://gogoanime3.co"; var BaseURL2 = "https://gogoanime3.co";
> 
> They are same
i know that but it makes less failure its like mirror server for api failure 
like server 1 dead
